Feature/dev 699 - [Melhorias Sprint 3]
decilioh/devel-food-gui pull request #46
Opened 2024-09-13 14:46 UTC by guilhermefshdevel

2024-09-13 17:58 UTC, tiago-pereira-develcode requested changes

2024-09-13 17:58 UTC, tiago-pereira-develcode commented on src/hooks/usePagination.ts
> +    const currentItems = (items: any[]) => items.slice(indexOfFirstItem, indexOfLastItem);
Especifique o tipo da variável `items` e evite o uso de `any`.

2024-09-13 17:58 UTC, tiago-pereira-develcode commented on src/mocks/promoMock.ts
> +        url: "https://media-cdn.tripadvisor.com/media/photo-s/17/29/87/21/promocao-do-restaurante.jpg"
Cuidado com os endpoints das imagens, pois o domínio pode mudar e aparecer uma imagem indesejada. Use sites com domínios confiáveis. 

https://images.pexels.com/photos/3022413/pexels-photo-3022413.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1

2024-09-13 18:38 UTC, guilhermefshdevel commented on src/hooks/usePagination.ts
> +    const currentItems = (items: any[]) => items.slice(indexOfFirstItem, indexOfLastItem);
Ajustei adicionando um tipo genério, agora fica: usePagination<TipoDoArray>.

2024-09-16 15:32 UTC, tiago-pereira-develcode approved these changes

2024-09-16 19:22 UTC, gabriel-decilio approved these changes

2024-09-16 19:22 UTC, merged